GET http://localhost:3000/api/v1/books HTTP/1.1
####

POST http://localhost:3000/api/v1/books HTTP/1.1
content-type: application/json

{
  "title": "Oryx and Crake",
  "authors": "Margaret Atwood",
  "description": "Oryx and Crake is at once an unforgettable love story and a compelling vision of the future. Snowman, known as Jimmy before mankind was overwhelmed by a plague, is struggling to survive in a world where he may be the last human, and mourning the loss of his best friend, Crake, and the beautiful and elusive Oryx whom they both loved. In search of answers, Snowman embarks on a journey–with the help of the green-eyed Children of Crake–through the lush wilderness that was so recently a great city, until powerful corporations took mankind on an uncontrolled genetic engineering ride. Margaret Atwood projects us into a near future that is both all too familiar and beyond our imagining.",
  "isAvailable": true
}
####

DELETE http://localhost:3000/api/v1/books/618b7c3b5596ed7e4c57fdd3
